export const COLLECTIONS = {
  INVITES: "invites",
  INVITE_TOKENS: "invitetokens",
  ORGANIZATIONS: "organizations",
  PROJECTS: "projects",
  REFRESH_TOKENS: "refreshtokens",
  TASKS: "tasks",
  MILESTONES: "milestones",
  USERS: "users",
  ORG_REGISTRATION_PENDING: "orgregistrationpendings",
  NOTIFICATIONS: "notifications",
  KANBAN_TEMPLATES: "kanbantemplates",
  COMMENTS: "comments",
  ATTACHMENTS: "attachments",
};
